import SwiftUI

/// A detailed view for displaying a specific recipe generated by the AI.
/// Features a brutalist UI with clear sections for ingredients and preparation steps.
struct RecipeDetailView: View {
    let recipe: SharedRecipe
    @Environment(\.dismiss) private var dismiss
    
    // Helper property to cleanly slice continuous paragraphs into distinct readable step items
    private var instructionSteps: [String] {
        recipe.instructions
            .components(separatedBy: CharacterSet(charactersIn: "\r\n."))
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty && $0.count > 3 } // Filters out accidental tracking artifacts or single-character dots
    }
    
    var body: some View {
        ScrollView(showsIndicators: false) {
            VStack(alignment: .leading, spacing: BrutalistTheme.spacingL) {
                
                // MARK: - RECIPE HEADER
                VStack(alignment: .leading, spacing: 12) {
                    Text(recipe.title.uppercased())
                        .font(.system(size: 28, weight: BrutalistTheme.fontBlack))
                        .foregroundColor(BrutalistTheme.brutalistBlack)
                        .fixedSize(horizontal: false, vertical: true)
                    
                    // Quick Specs Row (Time & Base Ingredient)
                    HStack(spacing: BrutalistTheme.spacingS) {
                        Label(recipe.time.uppercased(), systemImage: "timer")
                            .font(.system(size: 11, weight: BrutalistTheme.fontBlack))
                            .padding(.horizontal, 10)
                            .padding(.vertical, 6)
                            .brutalistBox(cornerRadius: 4, fillColor: BrutalistTheme.brutalistYellow, shadowOffset: 1)
                        
                        Label("\(recipe.highlightedIngredient.uppercased()) BASE", systemImage: "leaf.fill")
                            .font(.system(size: 11, weight: BrutalistTheme.fontBlack))
                            .padding(.horizontal, 10)
                            .padding(.vertical, 6)
                            .brutalistBox(cornerRadius: 4, fillColor: BrutalistTheme.brutalistCyan, shadowOffset: 1)
                    }
                }
                .padding(.top, BrutalistTheme.spacingM)
                
                // MARK: - INGREDIENTS SECTION
                VStack(alignment: .leading, spacing: BrutalistTheme.spacingM) {
                    Text("INGREDIENTS")
                        .font(.system(size: 18, weight: BrutalistTheme.fontBlack))
                        .foregroundColor(BrutalistTheme.brutalistBlack)
                        .padding(.bottom, 2)
                    
                    ForEach(recipe.ingredients, id: \.self) { ingredient in
                        HStack(spacing: BrutalistTheme.spacingM) {
                            Rectangle()
                                .stroke(BrutalistTheme.brutalistBlack, lineWidth: 2)
                                .frame(width: 16, height: 16)
                                .background(BrutalistTheme.brutalistWhite)
                            
                            Text(ingredient)
                                .font(.system(size: BrutalistTheme.bodyMedium, weight: .bold))
                                .foregroundColor(BrutalistTheme.brutalistBlack)
                        }
                    }
                }
                .padding(BrutalistTheme.spacingM)
                .frame(maxWidth: .infinity, alignment: .leading)
                .brutalistBox(
                    cornerRadius: BrutalistTheme.cornerRadiusMedium,
                    fillColor: BrutalistTheme.brutalistWhite,
                    shadowOffset: 4
                )
                
                // MARK: - PREPARATION STEPS
                VStack(alignment: .leading, spacing: BrutalistTheme.spacingM) {
                    Text("COOKING METHOD")
                        .font(.system(size: 18, weight: BrutalistTheme.fontBlack))
                        .foregroundColor(BrutalistTheme.brutalistBlack)
                        .padding(.bottom, 2)
                    
                    ForEach(Array(instructionSteps.enumerated()), id: \.offset) { index, step in
                        HStack(alignment: .top, spacing: BrutalistTheme.spacingM) {
                            // Step Number Circle
                            Text("\(index + 1)")
                                .font(.system(size: 14, weight: BrutalistTheme.fontBlack))
                                .foregroundColor(BrutalistTheme.brutalistBlack)
                                .frame(width: 28, height: 28)
                                .background(BrutalistTheme.brutalistCyan)
                                .border(BrutalistTheme.brutalistBlack, width: 2)
                            
                            Text(step)
                                .font(.system(size: BrutalistTheme.bodyMedium, weight: .medium))
                                .foregroundColor(BrutalistTheme.brutalistBlack)
                                .lineSpacing(4)
                                .fixedSize(horizontal: false, vertical: true)
                        }
                        .padding(.vertical, 4)
                    }
                }
                .padding(BrutalistTheme.spacingM)
                .frame(maxWidth: .infinity, alignment: .leading)
                .brutalistBox(
                    cornerRadius: BrutalistTheme.cornerRadiusMedium,
                    fillColor: BrutalistTheme.brutalistWhite,
                    shadowOffset: 4
                )
            }
            .padding(.horizontal, BrutalistTheme.spacingL)
            .padding(.bottom, 60)
        }
        .background(Color(hex: "#F5F5F5"))
        .navigationBarTitleDisplayMode(.inline)
        .navigationBarBackButtonHidden(true)
        .toolbar {
            ToolbarItem(placement: .navigationBarLeading) {
                Button(action: { dismiss() }) {
                    HStack(spacing: 6) {
                        Image(systemName: "arrow.left")
                            .font(.system(size: 14, weight: .bold))
                        Text("BACK")
                            .font(.system(size: 12, weight: BrutalistTheme.fontBlack))
                    }
                    .foregroundColor(BrutalistTheme.brutalistBlack)
                    .padding(.horizontal, 12)
                    .padding(.vertical, 8)
                    .background(BrutalistTheme.brutalistWhite)
                    .border(BrutalistTheme.brutalistBlack, width: 2)
                }
            }
        }
    }
}

// MARK: - PREVIEW CODE BLOCK
#Preview {
    NavigationStack {
        RecipeDetailView(
            recipe: SharedRecipe(
                title: "Viral Chili Crisp Ramen",
                description: "A super-fast, savory, and high-impact brutalist comfort food built around instant ramen noodles.",
                highlightedIngredient: "Ramen",
                ingredients: [
                    "1 Pack Instant Ramen",
                    "2 tbsp Chili Crisp Oil",
                    "1 Fresh Egg",
                    "1 tbsp Soy Sauce",
                    "Chopped Green Onions"
                ],
                time: "10 Mins",
                instructions: "Boil the noodles until soft. Mix soy sauce and chili crisp oil in a heavy bowl. Drain the boiling water. Toss ramen directly into the oil sauce. Top with a fried egg and onions."
            )
        )
    }
}
