import Foundation

/// Model representing a recipe generated by the AI or shared by users.
/// Resolves "Cannot find type 'SharedRecipe' in scope" errors.
struct SharedRecipe: Identifiable, Codable, Hashable {
    var id = UUID()
    let title: String
    let description: String
    let highlightedIngredient: String
    let ingredients: [String]
    let time: String
    let instructions: String
    
    // CodingKeys to match the JSON structure from Gemini
    // Ensure these match exactly what the AI prompt in RecipeService.swift expects
    enum CodingKeys: String, CodingKey {
        case title
        case description
        case highlightedIngredient
        case ingredients
        case time
        case instructions
    }
}
